apiVersion: v1
appVersion: "1.0"

description: A Chart for a HA postgres database
name: database
version: 0.1.1
kubeVersion: ">=v1.15.0"

keywords:
  - "SAP"
  - "vulnerability-assessment-tool"
  - "open-source"
  - "security-tools"
  - "java"
  - "python"
  - "maven"
  - "gradle"

home: https://sap.github.io/vulnerability-assessment-tool/
sources:
  - https://github.com/SAP/vulnerability-assessment-tool

maintainers:
  - name: "Quoc Trung HOANG"
    email: "quoc.trung.hoang@sap.com"
    url: ""

engine: gotpl
