apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "postgres.configMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  master.conf: |
    wal_level = replica
    max_wal_senders = 16
    wal_keep_segments = 1024
    max_wal_size = 30GB
    archive_mode = off
    # archive_command = 'cp "%p" "{{ .Values.postgres.master.pvcMountPath }}/archive/%f"'
    # archive_cleanup_command = 'pg_archivecleanup -d {{ .Values.postgres.master.pvcMountPath }}/archive %r'

    # INFO: extra user config
    {{- if .Values.postgres.master.extraConfigs }}
    {{- toYaml .Values.postgres.master.extraConfigs | nindent 2 }}
    {{- end }}

  pg_hba.conf: |
    # Allow any user on the local system to connect to any database with
    # any database user name using Unix-domain sockets (the default for local
    # connections).
    #
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    {{- with .Values.global.dbCredentials }}
    # Allow pgpooluser on the local system to connect to any database with
    # any database user name using Unix-domain sockets (the default for local
    # connections).
    #
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   {{ .pool_user }}     all                                     trust
    host    {{ .pool_user }}     all             127.0.0.1/32            trust
    host    {{ .pool_user }}     all             ::1/128                 trust
    host    {{ .pool_user }}     {{ .pool_user }}     all                     md5

    # Allow replication user on the local system to connect to any database with
    # any database user name using Unix-domain sockets (the default for local
    # connections).
    #
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   {{ .replication_user }}     all                                     trust
    host    {{ .replication_user }}     all             127.0.0.1/32            trust
    host    {{ .replication_user }}     all             ::1/128                 trust
    host    {{ .replication_user }}     {{ .replication_user }}     all                     md5
    host    all             all             all                     md5
    {{- end }}

  postgres.conf: |
    listen_addresses = '*'
    work_mem = 50MB
    maintenance_work_mem = 1024MB
    max_connections = 1000
    shared_buffers = 2048MB
    random_page_cost = 2.0
    autovacuum_max_workers = 8
    log_autovacuum_min_duration = '1s'
    autovacuum_vacuum_scale_factor = 0.15
    max_replication_slots = 10
    include_if_exists = 'master.conf'
    include_if_exists = 'replica.conf'
    {{- if .Values.postgres.debug }}
    log_min_messages = {{ .Values.postgres.debug }}
    {{- else }}
    # INFO: default value from helm chart
    log_min_messages = WARNING
    {{- end }}

  replica.conf: |
    hot_standby = on

    # wal_level = minimal
    # INFO: extra user config
    {{- if .Values.postgres.slave.extraConfigs }}
    {{- toYaml .Values.postgres.slave.extraConfigs | nindent 2 }}
    {{- end }}
