apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "postgres.script.configMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  01-postgres-users-setup.sh: |
    #!/bin/bash
    CHART_NAME="{{ template "postgres.master.name" . }}"
    LOG_ORIGIN="01-postgres-users-setup.sh"
    {{- include "logFunctions" . | nindent 4}}

    if [[ -z $POSTGRES_USER ]]; then
      _error "POSTGRES_USER cannot be empty"
    fi

    if [[ -z $POSTGRES_PASSWORD ]]; then
      _error "POSTGRES_PASSWORD cannot be empty"
    fi

    _info "INFO: Creating roles for pgpool and replicas"
    psql -v ON_ERROR_STOP=1 <<-EOSQL
      CREATE ROLE $REPLICATION_USER WITH REPLICATION ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}' LOGIN;
      CREATE ROLE $PGPOOL_USER WITH LOGIN ENCRYPTED PASSWORD '${PGPOOL_PASSWORD}';
      ALTER ROLE $PGPOOL_USER WITH SUPERUSER;
      ALTER ROLE $POSTGRES_USER WITH LOGIN ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}';
    EOSQL

  02-postgres-storage-setup.sh: |
    #!/bin/bash
    CHART_NAME="{{ template "postgres.master.name" . }}"
    LOG_ORIGIN="02-postgres-storage-setup.sh"
    {{- include "logFunctions" . | nindent 4}}

    _info "Creating default schemas for database"

    {{- $root := . }}
    {{- range $path, $bytes := .Files.Glob "files/**" }}
    _info "Executing $path"
    {{- $root.Files.Get $path | nindent 4 }}
    {{- end }}

  replica-init.sh: |-
    #!/bin/sh
    CHART_NAME="{{ template "postgres.slave.name" . }}"
    LOG_ORIGIN="replica-init.sh"
    {{- include "logFunctions" . | nindent 4}}

    {{- $release := .Release.Name }}
    until pg_isready -h {{ $release }}-db-master -p 5432; do
      _info "Postgres-master not ready, sleeping for {{ .Values.postgres.slave.backoffDuration }}"
      sleep {{ .Values.postgres.slave.backoffDuration }}
    done
    _info "Postgres master is ready"

    _info "Running pg_basebackup to catch up replication server...";
    pg_basebackup -R -h {{ $release }}-db-master -D $PGDATA -U $REPLICATION_USER
    _info "Fixing permissions for PGDATA"
    chown -R postgres:postgres $PGDATA

  master-poststart-hook.sh: |-
    #!/bin/sh
    CHART_NAME="{{ template "postgres.slave.name" . }}"
    LOG_ORIGIN="replica-init.sh"
    {{- include "logFunctions" . | nindent 4}}

    _info "Creating archive dir"
    mkdir -p {{ .Values.postgres.master.pvcMountPath }}/archive

    _info "Fixing permissions archive dir"
    chown -R postgres:postgres {{ .Values.postgres.master.pvcMountPath }}
    chown postgres:postgres {{ .Values.postgres.master.pvcMountPath }}/archive

  master-prestop-hook.sh: |-
    #!/bin/sh
    CHART_NAME="{{ template "postgres.slave.name" . }}"
    LOG_ORIGIN="replica-init.sh"
    {{- include "logFunctions" . | nindent 4}}

    _log "Gracefully shutting down"
    pg_ctl stop -m fast
