apiVersion: v1
kind: Secret

metadata:
  name: {{ template "pgpool.secretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  {{- with .Values.global.dbCredentials }}
  PCP_USER: {{ .pool_user | b64enc }}
  PCP_PASSWORD: {{ .pool_password | b64enc }}
  CHECK_USER: {{ .postgres_user | b64enc }}
  CHECK_PASSWORD: {{ .postgres_password | b64enc }}
  PG_USERNAME: {{ .postgres_user  | b64enc }}
  PG_PASSWORD: {{ .postgres_password | b64enc }}
  PGUSER: {{ .postgres_user  | b64enc }}
  PGPASSWORD: {{ .postgres_password | b64enc }}
  {{- end -}}
